public enum DreamPilotKit {
    public static let assets:[DreamRepresentation] = [
        .init(id:"whale_opal",concept:.seaCreatures,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[21, 114, 490, 399],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"seahorse_gold",concept:.seaCreatures,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[124, 22, 393, 492],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"jellyfish_lilac",concept:.seaCreatures,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[63, 37, 448, 480],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"manta_silk",concept:.seaCreatures,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[26, 26, 489, 483],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"eel_ribbon",concept:.seaCreatures,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[41, 26, 475, 487],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"nautilus_pearl",concept:.seaCreatures,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[23, 49, 491, 462],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"chicken_chef",concept:.culturalApparitions,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:5,alphaBounds:[106, 21, 419, 491],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"stove_chrome",concept:.culturalApparitions,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:5,alphaBounds:[83, 25, 475, 488],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"telephone_banana",concept:.culturalApparitions,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:5,alphaBounds:[32, 60, 480, 453],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"tv_cloud",concept:.culturalApparitions,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:5,alphaBounds:[46, 71, 468, 447],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"chair_velvet",concept:.chair,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[78, 24, 442, 487],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"bed_linen",concept:.bed,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[36, 43, 484, 453],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"window_aqua",concept:.window,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[35, 30, 477, 478],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"house_stilt",concept:.house,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[146, 19, 369, 490],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"rock_amethyst",concept:.rock,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[30, 31, 483, 482],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"water_curtain",concept:.water,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[109, 24, 408, 491],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"cloud_tower",concept:.cloud,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[81, 20, 432, 490],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"flower_orchid",concept:.flower,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[21, 24, 489, 486],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"ribbon_iridescent",concept:.ribbon,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[34, 33, 487, 486],pixelSize:[512,512],recommendedScaleRange:[20,180]),
        .init(id:"bubbles_pearl",concept:.water,medium:.surrealCGI,orientation:"collageCutout",moods:["dreamlike","uncanny"],paletteTags:["mixed"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[118, 42, 399, 476],pixelSize:[512,512],recommendedScaleRange:[20,180])
    ]
}
