/// Photo cutouts selected from the owner's Unsplash collection. Source records are in
/// data/dream_objects_intake.json; the original photographs remain untouched in DreamObjects/.
public enum DreamOwnerObjectKit {
    public static let assets:[DreamRepresentation] = [
        .init(id:"owner_orchid_purple",concept:.flower,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["purple"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[21,42,524,722],pixelSize:[582,760],recommendedScaleRange:[12,300]),
        .init(id:"owner_house_pink",concept:.house,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["pink"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[37,33,727,469],pixelSize:[760,523],recommendedScaleRange:[12,300]),
        .init(id:"owner_jellyfish_blue",concept:.seaCreatures,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["blue"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[36,47,474,713],pixelSize:[525,760],recommendedScaleRange:[12,300]),
        .init(id:"owner_horse_brown",concept:.horse,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["brown"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[121,26,600,424],pixelSize:[760,448],recommendedScaleRange:[12,300]),
        .init(id:"owner_tree_green",concept:.tree,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["green"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[34,28,729,498],pixelSize:[760,523],recommendedScaleRange:[12,300]),
        .init(id:"owner_moon_full",concept:.moon,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["gray"],depths:[.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[67,51,610,537],pixelSize:[760,582],recommendedScaleRange:[40,500]),
        .init(id:"owner_ribbon_iridescent",concept:.ribbon,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["iridescent"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[21,49,738,399],pixelSize:[760,448],recommendedScaleRange:[12,300]),
        .init(id:"owner_sun",concept:.star,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["orange"],depths:[.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[12,22,732,747],pixelSize:[760,760],recommendedScaleRange:[40,500]),
        .init(id:"owner_trojan_horse",concept:.horse,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["wood"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[116,31,563,729],pixelSize:[599,760],recommendedScaleRange:[12,300]),
        .init(id:"owner_moai",concept:.culturalApparitions,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["stone"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[132,32,372,735],pixelSize:[523,760],recommendedScaleRange:[12,300]),
        .init(id:"owner_candy_cane",concept:.culturalApparitions,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["red"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[24,41,482,708],pixelSize:[547,760],recommendedScaleRange:[12,300]),
        .init(id:"owner_dog",concept:.culturalApparitions,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["white"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[46,22,502,738],pixelSize:[515,760],recommendedScaleRange:[12,300]),
        .init(id:"owner_orange",concept:.culturalApparitions,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["orange"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[12,14,663,747],pixelSize:[714,760],recommendedScaleRange:[12,300]),
        .init(id:"owner_cloud_white",concept:.cloud,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["white"],depths:[.near,.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[12,45,746,503],pixelSize:[760,516],recommendedScaleRange:[12,300]),
        .init(id:"owner_arch_stone",concept:.arch,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["stone"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[12,60,563,718],pixelSize:[576,760],recommendedScaleRange:[12,300]),
        .init(id:"owner_tree_bare",concept:.tree,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["bare"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[17,44,496,747],pixelSize:[514,760],recommendedScaleRange:[12,300]),
        .init(id:"owner_house_miniature",concept:.house,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["miniature"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[73,26,679,556],pixelSize:[760,576],recommendedScaleRange:[12,300]),
        .init(id:"owner_horse_running",concept:.horse,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["brown"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[12,22,747,501],pixelSize:[760,514],recommendedScaleRange:[12,300]),
        .init(id:"owner_jupiter",concept:.moon,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["planet"],depths:[.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[50,54,709,705],pixelSize:[760,760],recommendedScaleRange:[40,500]),
        .init(id:"owner_mouth",concept:.culturalApparitions,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["red"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[120,27,741,474],pixelSize:[760,514],recommendedScaleRange:[12,300]),
        .init(id:"owner_house_keys",concept:.culturalApparitions,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["house","metal"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[38,23,698,549],pixelSize:[760,577],recommendedScaleRange:[12,300]),
        .init(id:"owner_seagull",concept:.culturalApparitions,medium:.photographic,orientation:"photoCutout",moods:["dreamlike","found"],paletteTags:["white"],depths:[.midground,.background],backgroundOnly:true,interactive:false,rarity:2,alphaBounds:[183,29,654,494],pixelSize:[760,514],recommendedScaleRange:[12,300]),
    ]
}
