import Foundation
import AppKit
import ImageIO
import UniformTypeIdentifiers
import CryptoKit

let root=URL(fileURLWithPath:FileManager.default.currentDirectoryPath)
let source=root.appendingPathComponent("DreamPlates")
let intakeManifest=root.appendingPathComponent("data/dream_objects_intake.json")
let intakeEntries=(try? JSONSerialization.jsonObject(with:Data(contentsOf:intakeManifest))) as? [[String:Any]] ?? []
let intakeByFile=Dictionary(uniqueKeysWithValues:intakeEntries.compactMap { entry -> (String,[String:Any])? in
    guard let file=entry["file"] as? String else {return nil}
    return (file,entry)
})
let output=root.appendingPathComponent("Dream Again/Resources/DreamPlates")
try FileManager.default.createDirectory(at:output,withIntermediateDirectories:true)
let files=try FileManager.default.contentsOfDirectory(at:source,includingPropertiesForKeys:nil).filter{["jpg","jpeg","png","heic"].contains($0.pathExtension.lowercased())}.sorted{$0.lastPathComponent<$1.lastPathComponent}
var entries:[[String:Any]]=[],lines:[String]=[],seen=Set<String>()
var thumbs:[(String,CGImage)]=[]
for url in files {
    let bytes=try Data(contentsOf:url)
    let digest=SHA256.hash(data:bytes).map{String(format:"%02x",$0)}.joined()
    guard seen.insert(digest).inserted else {continue}
    let id="plate_"+digest.prefix(16)
    guard let src=CGImageSourceCreateWithData(bytes as CFData,nil),let cg=CGImageSourceCreateThumbnailAtIndex(src,0,[kCGImageSourceCreateThumbnailFromImageAlways:true,kCGImageSourceCreateThumbnailWithTransform:true,kCGImageSourceThumbnailMaxPixelSize:2048] as CFDictionary) else {fatalError("Cannot decode \(url.lastPathComponent)")}
    let target=output.appendingPathComponent(id+".jpg")
    if !FileManager.default.fileExists(atPath:target.path) {
        let dest=CGImageDestinationCreateWithURL(target as CFURL,UTType.jpeg.identifier as CFString,1,nil)!
        CGImageDestinationAddImage(dest,cg,[kCGImageDestinationLossyCompressionQuality:0.84,kCGImagePropertyOrientation:1] as CFDictionary)
        guard CGImageDestinationFinalize(dest) else {fatalError("Cannot write \(id)")}
    }
    var record:[String:Any]=["id":id,"sourceFile":url.lastPathComponent,"sha256":digest,"width":cg.width,"height":cg.height,"source":"Owner-curated Unsplash download; original photo URL and photographer not supplied"]
    if let intake=intakeByFile[url.lastPathComponent],intake["role"] as? String == "plate" {
        record["source"]=intake["sourceURL"]
        record["licenseURL"]=intake["licenseURL"]
        record["tags"]=intake["tags"]
    }
    entries.append(record)
    lines.append("        .init(id:\"\(id)\",concept:nil,medium:.photographic,orientation:\"environmentPlate\",moods:[\"dreamlike\",\"atmospheric\"],paletteTags:[],depths:[.background],backgroundOnly:true,interactive:false,rarity:1,alphaBounds:[0,0,\(cg.width-1),\(cg.height-1)],pixelSize:[\(cg.width),\(cg.height)],recommendedScaleRange:[1000,6000])")
    let thumb=CGImageSourceCreateThumbnailAtIndex(src,0,[kCGImageSourceCreateThumbnailFromImageAlways:true,kCGImageSourceCreateThumbnailWithTransform:true,kCGImageSourceThumbnailMaxPixelSize:240] as CFDictionary)!
    thumbs.append((String(entries.count-1)+" · "+String(url.lastPathComponent.prefix(8)),thumb))
}
try ("// Generated by tools/import_dream_plates.swift. Do not hand-edit.\npublic enum DreamPlateLibrary {\n    public static let assets:[DreamRepresentation] = [\n"+lines.joined(separator:",\n")+"\n    ]\n}\n").write(to:root.appendingPathComponent("Dream Again/Core/DreamPlateLibrary.swift"),atomically:true,encoding:.utf8)
try JSONSerialization.data(withJSONObject:entries,options:[.prettyPrinted,.sortedKeys]).write(to:root.appendingPathComponent("data/dream_plates.json"),options:.atomic)
let evidence=root.appendingPathComponent("evidence")
for page in 0..<Int(ceil(Double(thumbs.count)/24)) {
    let image=NSImage(size:NSSize(width:1200,height:1080));image.lockFocus()
    NSColor.black.setFill();NSRect(x:0,y:0,width:1200,height:1080).fill()
    for i in page*24..<min(thumbs.count,(page+1)*24) {
        let n=i-page*24,x=(n%6)*200,y=1080-(n/6+1)*270
        let cg=thumbs[i].1,w=Double(cg.width),h=Double(cg.height),s=min(190/w,240/h)
        NSImage(cgImage:cg,size:.zero).draw(in:NSRect(x:Double(x)+(200-w*s)/2,y:Double(y)+25,width:w*s,height:h*s))
        (thumbs[i].0 as NSString).draw(at:NSPoint(x:x+6,y:y+5),withAttributes:[.foregroundColor:NSColor.white,.font:NSFont.systemFont(ofSize:12)])
    }
    image.unlockFocus()
    let data=NSBitmapImageRep(data:image.tiffRepresentation!)!.representation(using:.png,properties:[:])!
    try data.write(to:evidence.appendingPathComponent("plate-contact-\(page).png"))
}
print("Imported \(entries.count) unique plates from \(files.count) files")
